MLIR: mlir::LLVM::ModuleToObject Class Reference
mlir::LLVM::ModuleToObject Class Reference
Utility base class for transforming operations into binary objects, by default it returns the serialized LLVM bitcode for the module.
#include "mlir/Target/LLVM/ModuleToObject.h"
Public Member Functions
ModuleToObject (Operation &module, StringRef triple, StringRef chip, StringRef features={}, int optLevel=3)
virtual ~ModuleToObject ()=default
Operation & getOperation ()
Returns the operation being serialized.
virtual std::optional< SmallVector< char, 0 > > run ()
Runs the serialization pipeline, returning std::nullopt on error.
Protected Member Functions
virtual std::optional< SmallVector< std::unique_ptr< llvm::Module > > > loadBitcodeFiles (llvm::Module &module, llvm::TargetMachine &targetMachine)
Hook for loading bitcode files, returns std::nullopt on failure.
virtual LogicalResult handleBitcodeFile (llvm::Module &module, llvm::TargetMachine &targetMachine)
Hook for performing additional actions on a loaded bitcode file.
virtual void handleModulePreLink (llvm::Module &module, llvm::TargetMachine &targetMachine)
Hook for performing additional actions on the llvmModule pre linking.
virtual void handleModulePostLink (llvm::Module &module, llvm::TargetMachine &targetMachine)
Hook for performing additional actions on the llvmModule post linking.
virtual std::optional< SmallVector< char, 0 > > moduleToObject (llvm::Module &llvmModule, llvm::TargetMachine &targetMachine)
Serializes the LLVM IR bitcode to an object file, by default it serializes to LLVM bitcode.
std::unique_ptr< llvm::TargetMachine > createTargetMachine ()
Create the target machine based on the target triple and chip.
std::unique_ptr< llvm::Module > loadBitcodeFile (llvm::LLVMContext &context, llvm::TargetMachine &targetMachine, StringRef path)
Loads a bitcode file from path.
LogicalResult loadBitcodeFilesFromList (llvm::LLVMContext &context, llvm::TargetMachine &targetMachine, ArrayRef< std::string > fileList, SmallVector< std::unique_ptr< llvm::Module >> &llvmModules, bool failureOnError=true)
Loads multiple bitcode files.
std::unique_ptr< llvm::Module > translateToLLVMIR (llvm::LLVMContext &llvmContext)
Translates the operation to LLVM IR.
LogicalResult linkFiles (llvm::Module &module, SmallVector< std::unique_ptr< llvm::Module >> &&libs)
Link the llvmModule to other bitcode file.
LogicalResult optimizeModule (llvm::Module &module, llvm::TargetMachine &targetMachine, int optL)
Optimize the module.
Static Protected Member Functions
static std::optional< std::string > translateToISA (llvm::Module &llvmModule, llvm::TargetMachine &targetMachine)
Utility function for translating to ISA, returns std::nullopt on failure.
Protected Attributes
Operation & module
Module to transform to a binary object.
StringRef triple
Target triple.
StringRef chip
Target chip.
StringRef features
Target features.
int optLevel
Optimization level.
Detailed Description
Utility base class for transforming operations into binary objects, by default it returns the serialized LLVM bitcode for the module.
The operations being transformed must be translatable into LLVM IR.
Definition at line 30 of file ModuleToObject.h.
Constructor & Destructor Documentation
ModuleToObject()
ModuleToObject::ModuleToObject (Operation & module, StringRef triple, StringRef chip, StringRef features = {}, int optLevel = 3)
Definition at line 37 of file ModuleToObject.cpp.
~ModuleToObject()
virtual mlir::LLVM::ModuleToObject::~ModuleToObject () virtual default
Member Function Documentation
createTargetMachine()
std::unique_ptr< llvm::TargetMachine > ModuleToObject::createTargetMachine () protected
Create the target machine based on the target triple and chip.
Definition at line 44 of file ModuleToObject.cpp.
References chip, mlir::Operation::emitError(), features, getOperation(), and triple.
Referenced by run().
getOperation()
Operation & ModuleToObject::getOperation ()
Returns the operation being serialized.
Definition at line 42 of file ModuleToObject.cpp.
References module.
Referenced by mlir::NVVM::SerializeGPUModuleBase::appendStandardLibs(), createTargetMachine(), linkFiles(), loadBitcodeFile(), loadBitcodeFilesFromList(), optimizeModule(), run(), and translateToLLVMIR().
handleBitcodeFile()
virtual LogicalResult mlir::LLVM::ModuleToObject::handleBitcodeFile (llvm::Module & module, llvm::TargetMachine & targetMachine) inline protected virtual
Hook for performing additional actions on a loaded bitcode file.
Definition at line 52 of file ModuleToObject.h.
References mlir::success().
Referenced by loadBitcodeFile().
handleModulePostLink()
virtual void mlir::LLVM::ModuleToObject::handleModulePostLink (llvm::Module & module, llvm::TargetMachine & targetMachine) inline protected virtual
Hook for performing additional actions on the llvmModule post linking.
Definition at line 62 of file ModuleToObject.h.
Referenced by run().
handleModulePreLink()
virtual void mlir::LLVM::ModuleToObject::handleModulePreLink (llvm::Module & module, llvm::TargetMachine & targetMachine) inline protected virtual
Hook for performing additional actions on the llvmModule pre linking.
Definition at line 58 of file ModuleToObject.h.
Referenced by run().
linkFiles()
LogicalResult ModuleToObject::linkFiles (llvm::Module & module, SmallVector< std::unique_ptr< llvm::Module >> && libs) protected
Link the llvmModule to other bitcode file.
Definition at line 110 of file ModuleToObject.cpp.
References mlir::Operation::emitError(), mlir::failure(), getOperation(), module, and mlir::success().
Referenced by run().
loadBitcodeFile()
std::unique_ptr< llvm::Module > ModuleToObject::loadBitcodeFile (llvm::LLVMContext & context, llvm::TargetMachine & targetMachine, StringRef path) protected
Loads a bitcode file from path.
Definition at line 65 of file ModuleToObject.cpp.
References mlir::Operation::emitError(), mlir::failed(), getOperation(), and handleBitcodeFile().
Referenced by loadBitcodeFilesFromList().
loadBitcodeFiles()
virtual std::optional<SmallVector<std::unique_ptr<llvm::Module> > > mlir::LLVM::ModuleToObject::loadBitcodeFiles (llvm::Module & module, llvm::TargetMachine & targetMachine) inline protected virtual
Hook for loading bitcode files, returns std::nullopt on failure.
Reimplemented in mlir::NVVM::SerializeGPUModuleBase.
Definition at line 47 of file ModuleToObject.h.
Referenced by run().
loadBitcodeFilesFromList()
LogicalResult ModuleToObject::loadBitcodeFilesFromList (llvm::LLVMContext & context, llvm::TargetMachine & targetMachine, ArrayRef< std::string > fileList, SmallVector< std::unique_ptr< llvm::Module >> & llvmModules, bool failureOnError = true) protected
Loads multiple bitcode files.
Definition at line 82 of file ModuleToObject.cpp.
References mlir::Operation::emitError(), mlir::failure(), getOperation(), loadBitcodeFile(), and mlir::success().
Referenced by mlir::NVVM::SerializeGPUModuleBase::loadBitcodeFiles().
moduleToObject()
std::optional< SmallVector< char, 0 > > ModuleToObject::moduleToObject (llvm::Module & llvmModule, llvm::TargetMachine & targetMachine) protected virtual
Serializes the LLVM IR bitcode to an object file, by default it serializes to LLVM bitcode.
Definition at line 182 of file ModuleToObject.cpp.
Referenced by run().
optimizeModule()
LogicalResult ModuleToObject::optimizeModule (llvm::Module & module, llvm::TargetMachine & targetMachine, int optL) protected
Optimize the module.
Definition at line 139 of file ModuleToObject.cpp.
References mlir::Operation::emitError(), getOperation(), mlir::makeOptimizingTransformer(), module, optLevel, and mlir::success().
Referenced by run().
run()
std::optional< SmallVector< char, 0 > > ModuleToObject::run () virtual
Runs the serialization pipeline, returning std::nullopt on error.
Definition at line 191 of file ModuleToObject.cpp.
References createTargetMachine(), mlir::Operation::emitError(), mlir::failed(), getOperation(), handleModulePostLink(), handleModulePreLink(), linkFiles(), loadBitcodeFiles(), moduleToObject(), optimizeModule(), optLevel, and translateToLLVMIR().
translateToISA()
std::optional< std::string > ModuleToObject::translateToISA (llvm::Module & llvmModule, llvm::TargetMachine & targetMachine) static protected
Utility function for translating to ISA, returns std::nullopt on failure.
Definition at line 163 of file ModuleToObject.cpp.
translateToLLVMIR()
std::unique_ptr< llvm::Module > ModuleToObject::translateToLLVMIR (llvm::LLVMContext & llvmContext) protected
Translates the operation to LLVM IR.
Definition at line 105 of file ModuleToObject.cpp.
References getOperation(), and mlir::translateModuleToLLVMIR().
Referenced by run().
Member Data Documentation
chip
StringRef mlir::LLVM::ModuleToObject::chip protected
Target chip.
Definition at line 111 of file ModuleToObject.h.
Referenced by createTargetMachine().
features
StringRef mlir::LLVM::ModuleToObject::features protected
Target features.
Definition at line 114 of file ModuleToObject.h.
Referenced by createTargetMachine().
module
Operation& mlir::LLVM::ModuleToObject::module protected
Module to transform to a binary object.
Definition at line 105 of file ModuleToObject.h.
Referenced by getOperation(), linkFiles(), mlir::NVVM::SerializeGPUModuleBase::loadBitcodeFiles(), and optimizeModule().
optLevel
int mlir::LLVM::ModuleToObject::optLevel protected
Optimization level.
Definition at line 117 of file ModuleToObject.h.
Referenced by optimizeModule(), and run().
triple
StringRef mlir::LLVM::ModuleToObject::triple protected
Target triple.
Definition at line 108 of file ModuleToObject.h.
Referenced by createTargetMachine().
The documentation for this class was generated from the following files:
include/mlir/Target/LLVM/ModuleToObject.h
lib/Target/LLVM/ModuleToObject.cpp