MLIR: mlir::sparse_tensor::ir_detail::DimSpec Class Reference
mlir::sparse_tensor::ir_detail::DimSpec Class Reference final
The full dimVar = dimExpr : dimSlice specification for a given dimension.
#include "Dialect/SparseTensor/IR/Detail/DimLvlMap.h"
Public Member Functions
DimSpec (DimVar var, DimExpr expr, SparseTensorDimSliceAttr slice)
MLIRContext * tryGetContext () const
constexpr DimVar getBoundVar () const
bool hasExpr () const
constexpr DimExpr getExpr () const
void setExpr (DimExpr newExpr)
constexpr bool canElideExpr () const
void setElideExpr (bool b)
constexpr SparseTensorDimSliceAttr getSlice () const
bool isValid (Ranks const &ranks) const
Checks whether the variables bound/used by this spec are valid with respect to the given ranks.
bool isFunctionOf (Var var) const
bool isFunctionOf (VarSet const &vars) const
void getFreeVars (VarSet &vars) const
void print (llvm::raw_ostream &os, bool wantElision=true) const
void print (AsmPrinter &printer, bool wantElision=true) const
void dump () const
Detailed Description
The full dimVar = dimExpr : dimSlice specification for a given dimension.
Definition at line 197 of file DimLvlMap.h.
Constructor & Destructor Documentation
DimSpec()
DimSpec::DimSpec (DimVar var, DimExpr expr, SparseTensorDimSliceAttr slice)
Definition at line 177 of file DimLvlMap.cpp.
Member Function Documentation
canElideExpr()
constexpr bool mlir::sparse_tensor::ir_detail::DimSpec::canElideExpr () const inline constexpr
Definition at line 223 of file DimLvlMap.h.
dump()
void DimSpec::dump () const
Definition at line 192 of file DimLvlMap.cpp.
References print().
getBoundVar()
constexpr DimVar mlir::sparse_tensor::ir_detail::DimSpec::getBoundVar () const inline constexpr
Definition at line 216 of file DimLvlMap.h.
getExpr()
constexpr DimExpr mlir::sparse_tensor::ir_detail::DimSpec::getExpr () const inline constexpr
Definition at line 218 of file DimLvlMap.h.
getFreeVars()
void DimSpec::getFreeVars (VarSet & vars) const
Definition at line 190 of file DimLvlMap.cpp.
References mlir::sparse_tensor::ir_detail::VarSet::add().
getSlice()
constexpr SparseTensorDimSliceAttr mlir::sparse_tensor::ir_detail::DimSpec::getSlice () const inline constexpr
Definition at line 225 of file DimLvlMap.h.
Referenced by mlir::sparse_tensor::ir_detail::DimLvlMap::getDimSlice().
hasExpr()
bool mlir::sparse_tensor::ir_detail::DimSpec::hasExpr () const inline
Definition at line 217 of file DimLvlMap.h.
Referenced by setExpr().
isFunctionOf() [1/2]
bool mlir::sparse_tensor::ir_detail::DimSpec::isFunctionOf (Var var) const
isFunctionOf() [2/2]
bool DimSpec::isFunctionOf (VarSet const & vars) const
Definition at line 186 of file DimLvlMap.cpp.
References mlir::sparse_tensor::ir_detail::VarSet::occursIn().
isValid()
bool DimSpec::isValid (Ranks const & ranks) const
Checks whether the variables bound/used by this spec are valid with respect to the given ranks.
Note that null DimExpr is considered to be vacuously valid, and therefore calling setExpr invalidates the result of this predicate.
Definition at line 180 of file DimLvlMap.cpp.
References mlir::sparse_tensor::ir_detail::Ranks::isValid().
print() [1/2]
void DimSpec::print (AsmPrinter & printer, bool wantElision = true) const
Definition at line 196 of file DimLvlMap.cpp.
References mlir::AsmPrinter::getStream(), and print().
print() [2/2]
void DimSpec::print (llvm::raw_ostream & os, bool wantElision = true) const
Definition at line 199 of file DimLvlMap.cpp.
Referenced by dump(), print(), and mlir::sparse_tensor::ir_detail::DimLvlMap::print().
setElideExpr()
void mlir::sparse_tensor::ir_detail::DimSpec::setElideExpr (bool b) inline
Definition at line 224 of file DimLvlMap.h.
setExpr()
void mlir::sparse_tensor::ir_detail::DimSpec::setExpr (DimExpr newExpr) inline
Definition at line 219 of file DimLvlMap.h.
References hasExpr().
tryGetContext()
MLIRContext* mlir::sparse_tensor::ir_detail::DimSpec::tryGetContext () const inline
Definition at line 214 of file DimLvlMap.h.
References mlir::sparse_tensor::ir_detail::DimLvlExpr::tryGetContext().
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/IR/Detail/DimLvlMap.h
lib/Dialect/SparseTensor/IR/Detail/DimLvlMap.cpp