MLIR: mlir::sparse_tensor::ir_detail::DimLvlExpr Class Reference
mlir::sparse_tensor::ir_detail::DimLvlExpr Class Reference
#include "Dialect/SparseTensor/IR/Detail/DimLvlMap.h"
Public Member Functions
constexpr DimLvlExpr (ExprKind ek, AffineExpr expr)
constexpr bool operator== (DimLvlExpr other) const
constexpr bool operator!= (DimLvlExpr other) const
operator bool () const
template<typename U >
constexpr bool isa () const
template<typename U >
constexpr U cast () const
template<typename U >
constexpr U dyn_cast () const
constexpr ExprKind getExprKind () const
constexpr VarKind getAllowedVarKind () const
constexpr AffineExpr getAffineExpr () const
AffineExprKind getAffineKind () const
MLIRContext * tryGetContext () const
SymVar castSymVar () const
Var castDimLvlVar () const
int64_t castConstantValue () const
std::optional< int64_t > tryGetConstantValue () const
bool hasConstantValue (int64_t val) const
DimLvlExpr getLHS () const
DimLvlExpr getRHS () const
std::tuple< DimLvlExpr, AffineExprKind, DimLvlExpr > unpackBinop () const
bool isValid (Ranks const &ranks) const
Checks whether the variables bound/used by this spec are valid with respect to the given ranks.
void print (llvm::raw_ostream &os) const
void print (AsmPrinter &printer) const
void dump () const
Protected Types
enum class BindingStrength : bool { Weak = false , Strong = true }
Protected Member Functions
void printAffineExprInternal (llvm::raw_ostream &os, BindingStrength enclosingTightness) const
void printStrong (llvm::raw_ostream &os) const
void printWeak (llvm::raw_ostream &os) const
Detailed Description
Definition at line 48 of file DimLvlMap.h.
Member Enumeration Documentation
BindingStrength
enum mlir::sparse_tensor::ir_detail::DimLvlExpr::BindingStrength : bool strong protected
Enumerator
Weak
Strong
Definition at line 127 of file DimLvlMap.h.
Constructor & Destructor Documentation
DimLvlExpr()
constexpr mlir::sparse_tensor::ir_detail::DimLvlExpr::DimLvlExpr (ExprKind ek, AffineExpr expr) inline constexpr
Definition at line 61 of file DimLvlMap.h.
Referenced by getLHS(), and getRHS().
Member Function Documentation
cast()
template<typename U > constexpr U mlir::sparse_tensor::ir_detail::DimLvlExpr::cast constexpr
Definition at line 185 of file DimLvlMap.h.
castConstantValue()
int64_t DimLvlExpr::castConstantValue () const
Definition at line 27 of file DimLvlMap.cpp.
References mlir::AffineExpr::cast().
Referenced by printAffineExprInternal().
castDimLvlVar()
Var DimLvlExpr::castDimLvlVar () const
Definition at line 23 of file DimLvlMap.cpp.
References mlir::AffineExpr::cast(), and getAllowedVarKind().
Referenced by mlir::sparse_tensor::ir_detail::VarSet::add(), mlir::sparse_tensor::ir_detail::VarSet::occursIn(), and printAffineExprInternal().
castSymVar()
SymVar DimLvlExpr::castSymVar () const
Definition at line 19 of file DimLvlMap.cpp.
References mlir::AffineExpr::cast().
Referenced by mlir::sparse_tensor::ir_detail::VarSet::add(), mlir::sparse_tensor::ir_detail::VarSet::occursIn(), and printAffineExprInternal().
dump()
void DimLvlExpr::dump () const
Definition at line 70 of file DimLvlMap.cpp.
References print().
dyn_cast()
template<typename U > constexpr U mlir::sparse_tensor::ir_detail::DimLvlExpr::dyn_cast constexpr
Definition at line 191 of file DimLvlMap.h.
getAffineExpr()
constexpr AffineExpr mlir::sparse_tensor::ir_detail::DimLvlExpr::getAffineExpr () const inline constexpr
Definition at line 91 of file DimLvlMap.h.
Referenced by mlir::sparse_tensor::ir_detail::Ranks::isValid().
getAffineKind()
AffineExprKind mlir::sparse_tensor::ir_detail::DimLvlExpr::getAffineKind () const inline
Definition at line 92 of file DimLvlMap.h.
References mlir::AffineExpr::getKind().
Referenced by mlir::sparse_tensor::ir_detail::VarSet::add(), mlir::sparse_tensor::ir_detail::VarSet::occursIn(), printAffineExprInternal(), and unpackBinop().
getAllowedVarKind()
constexpr VarKind mlir::sparse_tensor::ir_detail::DimLvlExpr::getAllowedVarKind () const inline constexpr
Definition at line 88 of file DimLvlMap.h.
References mlir::sparse_tensor::ir_detail::getVarKindAllowedInExpr().
Referenced by castDimLvlVar(), and mlir::sparse_tensor::ir_detail::Ranks::isValid().
getExprKind()
constexpr ExprKind mlir::sparse_tensor::ir_detail::DimLvlExpr::getExprKind () const inline constexpr
Definition at line 87 of file DimLvlMap.h.
Referenced by mlir::sparse_tensor::ir_detail::DimExpr::classof(), mlir::sparse_tensor::ir_detail::LvlExpr::classof(), and isa().
getLHS()
DimLvlExpr DimLvlExpr::getLHS () const
Definition at line 51 of file DimLvlMap.cpp.
References DimLvlExpr(), and mlir::AffineExpr::dyn_cast_or_null().
getRHS()
DimLvlExpr DimLvlExpr::getRHS () const
Definition at line 56 of file DimLvlMap.cpp.
References DimLvlExpr(), and mlir::AffineExpr::dyn_cast_or_null().
hasConstantValue()
bool DimLvlExpr::hasConstantValue (int64_t val) const
Definition at line 46 of file DimLvlMap.cpp.
References mlir::AffineExpr::dyn_cast_or_null(), and mlir::AffineConstantExpr::getValue().
isa()
template<typename U > constexpr bool mlir::sparse_tensor::ir_detail::DimLvlExpr::isa constexpr
Definition at line 177 of file DimLvlMap.h.
References mlir::sparse_tensor::ir_detail::Dimension, getExprKind(), and mlir::sparse_tensor::ir_detail::Level.
isValid()
bool mlir::sparse_tensor::ir_detail::DimLvlExpr::isValid (Ranks const & ranks) const
Checks whether the variables bound/used by this spec are valid with respect to the given ranks.
operator bool()
mlir::sparse_tensor::ir_detail::DimLvlExpr::operator bool () const inline explicit
Definition at line 72 of file DimLvlMap.h.
operator!=()
constexpr bool mlir::sparse_tensor::ir_detail::DimLvlExpr::operator!= (DimLvlExpr other) const inline constexpr
Definition at line 69 of file DimLvlMap.h.
operator==()
constexpr bool mlir::sparse_tensor::ir_detail::DimLvlExpr::operator== (DimLvlExpr other) const inline constexpr
Definition at line 66 of file DimLvlMap.h.
print() [1/2]
void DimLvlExpr::print (AsmPrinter & printer) const
Definition at line 74 of file DimLvlMap.cpp.
References mlir::AsmPrinter::getStream(), and print().
print() [2/2]
void DimLvlExpr::print (llvm::raw_ostream & os) const
Definition at line 77 of file DimLvlMap.cpp.
References printWeak().
Referenced by dump(), and print().
printAffineExprInternal()
void DimLvlExpr::printAffineExprInternal (llvm::raw_ostream & os, BindingStrength enclosingTightness) const protected
Definition at line 107 of file DimLvlMap.cpp.
References mlir::Add, castConstantValue(), castDimLvlVar(), castSymVar(), mlir::CeilDiv, mlir::Constant, mlir::DimId, mlir::FloorDiv, getAffineKind(), mlir::Mod, mlir::Mul, Strong, and mlir::SymbolId.
Referenced by printStrong(), and printWeak().
printStrong()
void mlir::sparse_tensor::ir_detail::DimLvlExpr::printStrong (llvm::raw_ostream & os) const inline protected
Definition at line 134 of file DimLvlMap.h.
References printAffineExprInternal(), and Strong.
printWeak()
void mlir::sparse_tensor::ir_detail::DimLvlExpr::printWeak (llvm::raw_ostream & os) const inline protected
Definition at line 137 of file DimLvlMap.h.
References printAffineExprInternal(), and Weak.
Referenced by print().
tryGetConstantValue()
std::optional< int64_t > DimLvlExpr::tryGetConstantValue () const
Definition at line 31 of file DimLvlMap.cpp.
References mlir::AffineExpr::dyn_cast_or_null().
tryGetContext()
MLIRContext* mlir::sparse_tensor::ir_detail::DimLvlExpr::tryGetContext () const inline
Definition at line 96 of file DimLvlMap.h.
References mlir::AffineExpr::getContext().
Referenced by mlir::sparse_tensor::ir_detail::LvlSpec::getContext(), and mlir::sparse_tensor::ir_detail::DimSpec::tryGetContext().
unpackBinop()
std::tuple< DimLvlExpr, AffineExprKind, DimLvlExpr > DimLvlExpr::unpackBinop () const
Definition at line 62 of file DimLvlMap.cpp.
References mlir::AffineExpr::dyn_cast(), and getAffineKind().
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/IR/Detail/DimLvlMap.h
lib/Dialect/SparseTensor/IR/Detail/DimLvlMap.cpp