MLIR: mlir::sparse_tensor::ir_detail::LvlTypeParser Class Reference
mlir::sparse_tensor::ir_detail::LvlTypeParser Class Reference
#include "Dialect/SparseTensor/IR/Detail/LvlTypeParser.h"
Public Member Functions
LvlTypeParser ()
std::optional< DimLevelType > lookup (StringRef str) const
std::optional< DimLevelType > lookup (StringAttr str) const
ParseResult parseLvlType (AsmParser &parser, DimLevelType &out) const
FailureOr< DimLevelType > parseLvlType (AsmParser &parser) const
Detailed Description
Definition at line 47 of file LvlTypeParser.h.
Constructor & Destructor Documentation
LvlTypeParser()
mlir::sparse_tensor::ir_detail::LvlTypeParser::LvlTypeParser () inline explicit
Definition at line 51 of file LvlTypeParser.h.
Member Function Documentation
lookup() [1/2]
std::optional< DimLevelType > LvlTypeParser::lookup (StringAttr str) const
Definition at line 59 of file LvlTypeParser.cpp.
References lookup().
lookup() [2/2]
std::optional< DimLevelType > LvlTypeParser::lookup (StringRef str) const
Definition at line 49 of file LvlTypeParser.cpp.
Referenced by lookup(), and parseLvlType().
parseLvlType() [1/2]
FailureOr< DimLevelType > LvlTypeParser::parseLvlType (AsmParser & parser) const
Definition at line 63 of file LvlTypeParser.cpp.
References FAILURE_IF_FAILED, and parseLvlType().
parseLvlType() [2/2]
ParseResult LvlTypeParser::parseLvlType (AsmParser & parser, DimLevelType & out) const
Definition at line 69 of file LvlTypeParser.cpp.
References ERROR_IF, FAILURE_IF_FAILED, mlir::AsmParser::getCurrentLocation(), lookup(), mlir::AsmParser::parseOptionalKeyword(), and mlir::success().
Referenced by parseLvlType().
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/IR/Detail/LvlTypeParser.h
lib/Dialect/SparseTensor/IR/Detail/LvlTypeParser.cpp