MLIR: mlir::sparse_tensor::ir_detail::LvlSpec Class Reference
mlir::sparse_tensor::ir_detail::LvlSpec Class Reference final
The full lvlVar = lvlExpr : lvlType specification for a given level.
#include "Dialect/SparseTensor/IR/Detail/DimLvlMap.h"
Public Member Functions
LvlSpec (LvlVar var, LvlExpr expr, DimLevelType type)
MLIRContext * getContext () const
constexpr LvlVar getBoundVar () const
constexpr bool canElideVar () const
void setElideVar (bool b)
constexpr LvlExpr getExpr () const
constexpr DimLevelType getType () const
bool isValid (Ranks const &ranks) const
Checks whether the variables bound/used by this spec are valid with respect to the given ranks.
bool isFunctionOf (Var var) const
bool isFunctionOf (VarSet const &vars) const
void getFreeVars (VarSet &vars) const
void print (llvm::raw_ostream &os, bool wantElision=true) const
void print (AsmPrinter &printer, bool wantElision=true) const
void dump () const
Detailed Description
The full lvlVar = lvlExpr : lvlType specification for a given level.
Definition at line 248 of file DimLvlMap.h.
Constructor & Destructor Documentation
LvlSpec()
LvlSpec::LvlSpec (LvlVar var, LvlExpr expr, DimLevelType type)
Definition at line 215 of file DimLvlMap.cpp.
References mlir::sparse_tensor::isUndefDLT(), and mlir::sparse_tensor::isValidDLT().
Member Function Documentation
canElideVar()
constexpr bool mlir::sparse_tensor::ir_detail::LvlSpec::canElideVar () const inline constexpr
Definition at line 276 of file DimLvlMap.h.
dump()
void LvlSpec::dump () const
Definition at line 232 of file DimLvlMap.cpp.
References print().
getBoundVar()
constexpr LvlVar mlir::sparse_tensor::ir_detail::LvlSpec::getBoundVar () const inline constexpr
Definition at line 275 of file DimLvlMap.h.
Referenced by mlir::sparse_tensor::ir_detail::DimLvlMap::print().
getContext()
MLIRContext* mlir::sparse_tensor::ir_detail::LvlSpec::getContext () const inline
Definition at line 269 of file DimLvlMap.h.
References mlir::sparse_tensor::ir_detail::DimLvlExpr::tryGetContext().
getExpr()
constexpr LvlExpr mlir::sparse_tensor::ir_detail::LvlSpec::getExpr () const inline constexpr
Definition at line 278 of file DimLvlMap.h.
getFreeVars()
void LvlSpec::getFreeVars (VarSet & vars) const
Definition at line 230 of file DimLvlMap.cpp.
References mlir::sparse_tensor::ir_detail::VarSet::add().
getType()
constexpr DimLevelType mlir::sparse_tensor::ir_detail::LvlSpec::getType () const inline constexpr
Definition at line 279 of file DimLvlMap.h.
Referenced by mlir::sparse_tensor::ir_detail::DimLvlMap::getLvlType().
isFunctionOf() [1/2]
bool mlir::sparse_tensor::ir_detail::LvlSpec::isFunctionOf (Var var) const
isFunctionOf() [2/2]
bool LvlSpec::isFunctionOf (VarSet const & vars) const
Definition at line 226 of file DimLvlMap.cpp.
References mlir::sparse_tensor::ir_detail::VarSet::occursIn().
isValid()
bool LvlSpec::isValid (Ranks const & ranks) const
Checks whether the variables bound/used by this spec are valid with respect to the given ranks.
Definition at line 221 of file DimLvlMap.cpp.
References mlir::sparse_tensor::ir_detail::Ranks::isValid().
print() [1/2]
void LvlSpec::print (AsmPrinter & printer, bool wantElision = true) const
Definition at line 236 of file DimLvlMap.cpp.
References mlir::AsmPrinter::getStream(), and print().
print() [2/2]
void LvlSpec::print (llvm::raw_ostream & os, bool wantElision = true) const
Definition at line 239 of file DimLvlMap.cpp.
References mlir::sparse_tensor::toMLIRString().
Referenced by dump(), and print().
setElideVar()
void mlir::sparse_tensor::ir_detail::LvlSpec::setElideVar (bool b) inline
Definition at line 277 of file DimLvlMap.h.
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/IR/Detail/DimLvlMap.h
lib/Dialect/SparseTensor/IR/Detail/DimLvlMap.cpp