MLIR: lib/Dialect/GPU/TransformOps/GPUTransformOps.cpp File Reference
GPUTransformOps.cpp File Reference
#include "mlir/Dialect/GPU/TransformOps/GPUTransformOps.h"
#include "mlir/Conversion/GPUCommon/GPUCommonPass.h"
#include "mlir/Conversion/GPUToNVVM/GPUToNVVMPass.h"
#include "mlir/Conversion/LLVMCommon/TypeConverter.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/GPU/TransformOps/Utils.h"
#include "mlir/Dialect/GPU/Transforms/Passes.h"
#include "mlir/Dialect/LLVMIR/NVVMDialect.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/DeviceMappingInterface.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Transform/IR/TransformInterfaces.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Transforms/VectorTransforms.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/Visitors.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "mlir/Dialect/GPU/TransformOps/GPUTransformOps.cpp.inc"
Classes
struct ForallRewriteResult
Struct to return the result of the rewrite of a forall operation.
Macros
#define DEBUG_TYPE "gpu-transforms"
#define DEBUG_TYPE_ALIAS "gpu-transforms-alias"
#define DBGS() (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
#define LDBG(X) LLVM_DEBUG(DBGS() << X << "\n")
#define DBGS_ALIAS() (llvm::dbgs() << '[' << DEBUG_TYPE_ALIAS << "] ")
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static std::optional< SmallVector< int64_t > > gpuMmaUnrollOrder (vector::ContractionOp contract)
Pick an unrolling order that will allow tensorcore operation to reuse LHS register.
static std::optional< SmallVector< int64_t > > getSubgroupMmaNativeVectorSize (Operation *op, int64_t m, int64_t n, int64_t k)
Returns the target vector size for the target operation based on the native vector size specified with m, n, and k.
static bool isKnownNoEffectsOpWithoutInterface (Operation *op)
Implement the MemoryEffectsOpInterface in the suitable way.
static bool isParallelRegionBoundary (Operation *op)
Returns true if the op is defines the parallel region that is subject to barrier synchronization.
static bool isSequentialLoopLike (Operation *op)
Returns true if the op behaves like a sequential loop, e.g., the control flow "wraps around" from the end of the body region back to its start.
static bool hasSingleExecutionBody (Operation *op)
Returns true if the regions of the op are guaranteed to be executed at most once.
static bool producesDistinctBase (Operation *op)
Returns true if the operation is known to produce a pointer-like object distinct from any other object produced by a similar operation.
static void addAllValuelessEffects (SmallVectorImpl< MemoryEffects::EffectInstance > &effects)
Populates effects with all memory effects without associating them to a specific value.
static bool collectEffects (Operation *op, SmallVectorImpl< MemoryEffects::EffectInstance > &effects, bool ignoreBarriers=true)
Collect the memory effects of the given op in 'effects'.
bool getEffectsBefore (Operation *op, SmallVectorImpl< MemoryEffects::EffectInstance > &effects, bool stopAtBarrier)
Collects memory effects from operations that may be executed before op in a trivial structured control flow, e.g., without branches.
bool getEffectsAfter (Operation *op, SmallVectorImpl< MemoryEffects::EffectInstance > &effects, bool stopAtBarrier)
Collects memory effects from operations that may be executed after op in a trivial structured control flow, e.g., without branches.
static Value getBase (Value v)
Looks through known "view-like" ops to find the base memref.
static bool isFunctionArgument (Value v)
Returns true if the value is defined as a function argument.
static Value propagatesCapture (Operation *op)
Returns the operand that the operation "propagates" through it for capture purposes.
static std::optional< bool > getKnownCapturingStatus (Operation *op, Value v)
Returns true if the given operation is known to capture the given value, false if it is known not to capture the given value, nullopt if neither is known.
bool maybeCaptured (Value v)
Returns true if the value may be captured by any of its users, i.e., if the user may be storing this value into memory.
static bool mayAlias (Value first, Value second)
Returns true if two values may be referencing aliasing memory.
bool mayAlias (MemoryEffects::EffectInstance a, Value v2)
Returns true if the effect may be affecting memory aliasing the value.
bool mayAlias (MemoryEffects::EffectInstance a, MemoryEffects::EffectInstance b)
Returns true if the two effects may be affecting aliasing memory.
static bool haveConflictingEffects (ArrayRef< MemoryEffects::EffectInstance > beforeEffects, ArrayRef< MemoryEffects::EffectInstance > afterEffects)
Returns true if any of the "before" effect instances has a conflict with any "after" instance for the purpose of barrier elimination.
static DiagnosedSilenceableFailure definiteFailureHelper (std::optional< TransformOpInterface > transformOp, Operation *target, const Twine &message)
static DiagnosedSilenceableFailure checkMappingAttributeTypes (std::optional< TransformOpInterface > transformOp, scf::ForallOp forallOp)
Check if given mapping attributes are one of the desired attributes.
static DiagnosedSilenceableFailure verifyGpuMapping (std::optional< TransformOpInterface > transformOp, scf::ForallOp forallOp)
template<typename OpTy , typename OperationOrBlock >
static void replaceUnitMappingIdsHelper (RewriterBase &rewriter, Location loc, OperationOrBlock *parent, Value replacement, ArrayRef< int64_t > availableMappingSizes)
Helper to replace ids of dimensions known to be 1 by 0 to simplify the IR.
static DiagnosedSilenceableFailure rewriteOneForallCommonImpl (RewriterBase &rewriter, std::optional< TransformOpInterface > transformOp, scf::ForallOp forallOp, ArrayRef< int64_t > availableMappingSizes, ForallRewriteResult &result, const GpuIdBuilder &gpuIdBuilder)
static DiagnosedSilenceableFailure checkMappingSpec (std::optional< TransformOpInterface > transformOp, scf::ForallOp forallOp, ArrayRef< int64_t > numParallelIterations, ArrayRef< int64_t > blockOrGridSizes, int factor, bool useLinearMapping=false)
static DiagnosedSilenceableFailure getThreadIdBuilder (std::optional< TransformOpInterface > transformOp, scf::ForallOp forallOp, ArrayRef< int64_t > blockSizes, int64_t warpSize, GpuIdBuilder &gpuIdBuilder)
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 52 of file GPUTransformOps.cpp.
DBGS_ALIAS
#define DBGS_ALIAS () (llvm::dbgs() << '[' << DEBUG_TYPE_ALIAS << "] ")
Definition at line 54 of file GPUTransformOps.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "gpu-transforms"
Definition at line 49 of file GPUTransformOps.cpp.
DEBUG_TYPE_ALIAS
#define DEBUG_TYPE_ALIAS "gpu-transforms-alias"
Definition at line 50 of file GPUTransformOps.cpp.
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1466 of file GPUTransformOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
LDBG
#define LDBG (X) LLVM_DEBUG(DBGS() << X << "\n")
Definition at line 53 of file GPUTransformOps.cpp.
Function Documentation
addAllValuelessEffects()
static void addAllValuelessEffects (SmallVectorImpl< MemoryEffects::EffectInstance > & effects) static
Populates effects with all memory effects without associating them to a specific value.
Definition at line 304 of file GPUTransformOps.cpp.
checkMappingAttributeTypes()
static DiagnosedSilenceableFailure checkMappingAttributeTypes (std::optional< TransformOpInterface > transformOp, scf::ForallOp forallOp) static
Check if given mapping attributes are one of the desired attributes.
Definition at line 848 of file GPUTransformOps.cpp.
References definiteFailureHelper(), and mlir::DiagnosedSilenceableFailure::success().
Referenced by verifyGpuMapping().
checkMappingSpec()
static DiagnosedSilenceableFailure checkMappingSpec (std::optional< TransformOpInterface > transformOp, scf::ForallOp forallOp, ArrayRef< int64_t > numParallelIterations, ArrayRef< int64_t > blockOrGridSizes, int factor, bool useLinearMapping = false) static
Definition at line 1271 of file GPUTransformOps.cpp.
References mlir::computeProduct(), definiteFailureHelper(), diag(), and mlir::DiagnosedSilenceableFailure::success().
Referenced by getThreadIdBuilder().
collectEffects()
static bool collectEffects (Operation * op, SmallVectorImpl< MemoryEffects::EffectInstance > & effects, bool ignoreBarriers = true) static
Collect the memory effects of the given op in 'effects'.
Returns 'true' if it could extract the effect information from the op, otherwise returns 'false' and conservatively populates the list with all possible effects associated with no particular value or symbol.
Definition at line 317 of file GPUTransformOps.cpp.
definiteFailureHelper()
static DiagnosedSilenceableFailure definiteFailureHelper (std::optional< TransformOpInterface > transformOp, Operation * target, const Twine & message) static
Definition at line 839 of file GPUTransformOps.cpp.
References mlir::emitDefiniteFailure().
Referenced by checkMappingAttributeTypes(), checkMappingSpec(), getThreadIdBuilder(), mlir::transform::gpu::mapNestedForallToThreadsImpl(), rewriteOneForallCommonImpl(), and verifyGpuMapping().
getBase()
static Value getBase (Value v) static
Looks through known "view-like" ops to find the base memref.
Definition at line 517 of file GPUTransformOps.cpp.
References mlir::Value::getDefiningOp().
Referenced by llvm::DenseMapInfo< mlir::SuccessorRange >::isEqual(), mlir::OperandRangeRange::join(), mlir::MutableOperandRangeRange::join(), mayAlias(), and mlir::MutableOperandRangeRange::operator OperandRangeRange().
getEffectsAfter()
bool getEffectsAfter (Operation * op, SmallVectorImpl< MemoryEffects::EffectInstance > & effects, bool stopAtBarrier)
Collects memory effects from operations that may be executed after op in a trivial structured control flow, e.g., without branches.
Stops at the parallel region boundary or at the barrier operation if stopAtBarrier is set. Returns true if the memory effects added to effects are exact, false if they are a conservative over-approximation. The latter means that effects contain instances not associated with a specific value.
Definition at line 441 of file GPUTransformOps.cpp.
getEffectsBefore()
bool getEffectsBefore (Operation * op, SmallVectorImpl< MemoryEffects::EffectInstance > & effects, bool stopAtBarrier)
Collects memory effects from operations that may be executed before op in a trivial structured control flow, e.g., without branches.
Stops at the parallel region boundary or at the barrier operation if stopAtBarrier is set. Returns true if the memory effects added to effects are exact, false if they are a conservative over-approximation. The latter means that effects contain instances not associated with a specific value.
Definition at line 362 of file GPUTransformOps.cpp.
getKnownCapturingStatus()
static std::optional<bool> getKnownCapturingStatus (Operation * op, Value v) static
Returns true if the given operation is known to capture the given value, false if it is known not to capture the given value, nullopt if neither is known.
Definition at line 568 of file GPUTransformOps.cpp.
Referenced by maybeCaptured().
getSubgroupMmaNativeVectorSize()
static std::optional<SmallVector<int64_t> > getSubgroupMmaNativeVectorSize (Operation * op, int64_t m, int64_t n, int64_t k) static
Returns the target vector size for the target operation based on the native vector size specified with m, n, and k.
Definition at line 173 of file GPUTransformOps.cpp.
getThreadIdBuilder()
static DiagnosedSilenceableFailure getThreadIdBuilder (std::optional< TransformOpInterface > transformOp, scf::ForallOp forallOp, ArrayRef< int64_t > blockSizes, int64_t warpSize, GpuIdBuilder & gpuIdBuilder) static
Definition at line 1297 of file GPUTransformOps.cpp.
References checkMappingSpec(), definiteFailureHelper(), diag(), mlir::getConstantIntValues(), and mlir::DiagnosedSilenceableFailure::success().
Referenced by mlir::transform::gpu::mapOneForallToThreadsImpl().
gpuMmaUnrollOrder()
static std::optional<SmallVector<int64_t> > gpuMmaUnrollOrder (vector::ContractionOp contract) static
Pick an unrolling order that will allow tensorcore operation to reuse LHS register.
Definition at line 142 of file GPUTransformOps.cpp.
References contract(), mlir::detail::enumerate(), mlir::AffineDimExpr::getPosition(), mlir::vector::isParallelIterator(), and mlir::vector::isReductionIterator().
hasSingleExecutionBody()
static bool hasSingleExecutionBody (Operation * op) static
Returns true if the regions of the op are guaranteed to be executed at most once.
Thus, if an operation in one of the nested regions of op is executed than so are all the other operations in this region.
Definition at line 291 of file GPUTransformOps.cpp.
haveConflictingEffects()
static bool haveConflictingEffects (ArrayRef< MemoryEffects::EffectInstance > beforeEffects, ArrayRef< MemoryEffects::EffectInstance > afterEffects) static
Returns true if any of the "before" effect instances has a conflict with any "after" instance for the purpose of barrier elimination.
The effects are supposed to be limited to a barrier synchronization scope. A conflict exists if effects instances affect aliasing memory locations and at least on of then as a write. As an exception, if the non-write effect is an allocation effect, there is no conflict since we are only expected to see the allocation happening in the same thread and it cannot be accessed from another thread without capture (which we do handle in alias analysis).
Definition at line 738 of file GPUTransformOps.cpp.
References DBGS, and mayAlias().
isFunctionArgument()
static bool isFunctionArgument (Value v) static
Returns true if the value is defined as a function argument.
Definition at line 546 of file GPUTransformOps.cpp.
Referenced by mayAlias().
isKnownNoEffectsOpWithoutInterface()
static bool isKnownNoEffectsOpWithoutInterface (Operation * op) static
Implement the MemoryEffectsOpInterface in the suitable way.
Definition at line 269 of file GPUTransformOps.cpp.
isParallelRegionBoundary()
static bool isParallelRegionBoundary (Operation * op) static
Returns true if the op is defines the parallel region that is subject to barrier synchronization.
Definition at line 277 of file GPUTransformOps.cpp.
isSequentialLoopLike()
static bool isSequentialLoopLike (Operation * op) static
Returns true if the op behaves like a sequential loop, e.g., the control flow "wraps around" from the end of the body region back to its start.
Definition at line 286 of file GPUTransformOps.cpp.
mayAlias() [1/3]
bool mayAlias (MemoryEffects::EffectInstance a, MemoryEffects::EffectInstance b)
Returns true if the two effects may be affecting aliasing memory.
If an effect is not associated with any value, it is assumed to affect all memory and therefore aliases with everything. Effects on different resources cannot alias.
Definition at line 717 of file GPUTransformOps.cpp.
References mlir::SideEffects::EffectInstance< EffectT >::getResource(), mlir::SideEffects::Resource::getResourceID(), mlir::SideEffects::EffectInstance< EffectT >::getValue(), and mayAlias().
mayAlias() [2/3]
bool mayAlias (MemoryEffects::EffectInstance a, Value v2)
Returns true if the effect may be affecting memory aliasing the value.
If the effect is not associated with any value, it is assumed to affect all memory and therefore aliases with everything.
Definition at line 706 of file GPUTransformOps.cpp.
References mlir::SideEffects::EffectInstance< EffectT >::getValue(), and mayAlias().
mayAlias() [3/3]
static bool mayAlias (Value first, Value second) static
Returns true if two values may be referencing aliasing memory.
This is a rather naive and conservative analysis. Values defined by different allocation-like operations as well as values derived from those by casts and views cannot alias each other. Similarly, values defined by allocations inside a function cannot alias function arguments. Global values cannot alias each other or local allocations. Values that are captured, i.e. themselves potentially stored in memory, are considered as aliasing with everything. This seems sufficient to achieve barrier removal in structured control flow, more complex cases would require a proper dataflow analysis.
Definition at line 629 of file GPUTransformOps.cpp.
References DBGS_ALIAS, DEBUG_TYPE_ALIAS, getBase(), mlir::Value::getDefiningOp(), isFunctionArgument(), maybeCaptured(), and producesDistinctBase().
Referenced by haveConflictingEffects(), and mayAlias().
maybeCaptured()
bool maybeCaptured (Value v)
Returns true if the value may be captured by any of its users, i.e., if the user may be storing this value into memory.
This makes aliasing analysis more conservative as it cannot assume the pointer-like value is only passed around through SSA use-def.
Definition at line 586 of file GPUTransformOps.cpp.
References mlir::SideEffects::EffectInstance< EffectT >::getEffect(), getKnownCapturingStatus(), mlir::Value::getUsers(), and propagatesCapture().
Referenced by mayAlias().
producesDistinctBase()
static bool producesDistinctBase (Operation * op) static
Returns true if the operation is known to produce a pointer-like object distinct from any other object produced by a similar operation.
For example, an allocation produces such an object.
Definition at line 298 of file GPUTransformOps.cpp.
Referenced by mayAlias().
propagatesCapture()
static Value propagatesCapture (Operation * op) static
Returns the operand that the operation "propagates" through it for capture purposes.
That is, if the value produced by this operation is captured, then so is the returned value.
Definition at line 554 of file GPUTransformOps.cpp.
Referenced by maybeCaptured().
replaceUnitMappingIdsHelper()
template<typename OpTy , typename OperationOrBlock > static void replaceUnitMappingIdsHelper (RewriterBase & rewriter, Location loc, OperationOrBlock * parent, Value replacement, ArrayRef< int64_t > availableMappingSizes) static
Helper to replace ids of dimensions known to be 1 by 0 to simplify the IR.
Definition at line 955 of file GPUTransformOps.cpp.
References mlir::RewriterBase::replaceAllUsesWith().
rewriteOneForallCommonImpl()
static DiagnosedSilenceableFailure rewriteOneForallCommonImpl (RewriterBase & rewriter, std::optional< TransformOpInterface > transformOp, scf::ForallOp forallOp, ArrayRef< int64_t > availableMappingSizes, ForallRewriteResult & result, const GpuIdBuilder & gpuIdBuilder) static
Definition at line 964 of file GPUTransformOps.cpp.
References mlir::transform::gpu::IdBuilderResult::activeIdOps, mlir::transform::gpu::IdBuilderResult::activeMappingSizes, mlir::transform::gpu::IdBuilderResult::availableMappingSizes, mlir::Block::begin(), mlir::OpBuilder::create(), DBGS, definiteFailureHelper(), diag(), mlir::RewriterBase::eraseOp(), mlir::Block::front(), mlir::getConstantIntValues(), mlir::OpBuilder::getInsertionPoint(), mlir::Block::getOperations(), mlir::getValuesSortedByKey(), mlir::transform::gpu::GpuIdBuilder::idBuilder, LDBG, mlir::IRMapping::lookup(), mlir::IRMapping::map(), mlir::transform::gpu::GpuIdBuilder::mappingAttributes, mlir::transform::gpu::IdBuilderResult::mappingIdOps, mlir::RewriterBase::replaceAllUsesWith(), mlir::OpBuilder::setInsertionPoint(), mlir::DiagnosedSilenceableFailure::success(), and verifyGpuMapping().
Referenced by mlir::transform::gpu::mapForallToBlocksImpl(), and mlir::transform::gpu::mapOneForallToThreadsImpl().
verifyGpuMapping()
static DiagnosedSilenceableFailure verifyGpuMapping (std::optional< TransformOpInterface > transformOp, scf::ForallOp forallOp) static
Definition at line 906 of file GPUTransformOps.cpp.
References checkMappingAttributeTypes(), definiteFailureHelper(), mlir::getConstantIntValues(), mlir::DiagnosedSilenceableFailure::succeeded(), and mlir::DiagnosedSilenceableFailure::success().
Referenced by rewriteOneForallCommonImpl().