MLIR: lib/Dialect/MemRef/Transforms/EmulateNarrowType.cpp File Reference
EmulateNarrowType.cpp File Reference
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Transforms/NarrowTypeEmulationConverter.h"
#include "mlir/Dialect/Arith/Transforms/Passes.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/Transforms/Passes.h"
#include "mlir/Dialect/MemRef/Transforms/Transforms.h"
#include "mlir/Dialect/MemRef/Utils/MemRefUtils.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/MathExtras.h"
#include <cassert>
Functions
static Value getOffsetForBitwidth (Location loc, Value srcIdx, int sourceBits, int targetBits, OpBuilder &builder)
When data is loaded/stored in targetBits granularity, but is used in sourceBits granularity (sourceBits < targetBits), the targetBits is treated as an array of elements of width sourceBits.
Function Documentation
getOffsetForBitwidth()
static Value getOffsetForBitwidth (Location loc, Value srcIdx, int sourceBits, int targetBits, OpBuilder & builder) static
When data is loaded/stored in targetBits granularity, but is used in sourceBits granularity (sourceBits < targetBits), the targetBits is treated as an array of elements of width sourceBits.
Return the bit offset of the value at position srcIdx. For example, if sourceBits equals to 4 and targetBits equals to 8, the x-th element is located at (x % 2) * 4. Because there are two elements in one i8, and one element has 4 bits.
Definition at line 38 of file EmulateNarrowType.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getIntegerAttr(), and mlir::Builder::getIntegerType().