MLIR: mlir::arm_sme Namespace Reference
mlir::arm_sme Namespace Reference
Classes
class ArmSMETypeConverter
Enumerations
enum class ArmStreaming { Default = 0 , Locally = 1 }
Functions
std::unique_ptr< Pass > createEnableArmStreamingPass (const ArmStreaming mode=ArmStreaming::Default, const bool enableZA=false)
Pass to enable Armv9 Streaming SVE mode.
std::unique_ptr< Pass > createTileAllocationPass ()
Pass that replaces 'arm_sme.get_tile_id' ops with actual tiles.
void populateVectorTransferLoweringPatterns (LLVMTypeConverter &converter, RewritePatternSet &patterns)
unsigned getSMETileSliceMinNumElts (Type type)
Return minimum number of elements for the given element type in a vector of SVL bits.
bool isValidSMETileElementType (Type type)
Returns true if type is a valid element type for an SME tile or false otherwise.
bool isValidSMETileVectorType (VectorType vType)
Returns true if vType is a valid vector type for an SME tile or false otherwise.
Enumeration Type Documentation
ArmStreaming
enum mlir::arm_sme::ArmStreaming strong
Enumerator
Default
Locally
Definition at line 27 of file Passes.h.
Function Documentation
createEnableArmStreamingPass()
std::unique_ptr< Pass > mlir::arm_sme::createEnableArmStreamingPass (const ArmStreaming mode = ArmStreaming::Default, const bool enableZA = false)
Pass to enable Armv9 Streaming SVE mode.
Definition at line 86 of file EnableArmStreaming.cpp.
createTileAllocationPass()
std::unique_ptr< Pass > mlir::arm_sme::createTileAllocationPass ()
Pass that replaces 'arm_sme.get_tile_id' ops with actual tiles.
Definition at line 196 of file TileAllocation.cpp.
getSMETileSliceMinNumElts()
unsigned mlir::arm_sme::getSMETileSliceMinNumElts (Type type)
Return minimum number of elements for the given element type in a vector of SVL bits.
Definition at line 22 of file Utils.cpp.
References mlir::Type::getIntOrFloatBitWidth(), isValidSMETileElementType(), and MinStreamingVectorLengthInBits.
Referenced by isValidSMETileVectorType().
isValidSMETileElementType()
bool mlir::arm_sme::isValidSMETileElementType (Type type)
Returns true if type is a valid element type for an SME tile or false otherwise.
Definition at line 27 of file Utils.cpp.
References mlir::Type::isBF16(), mlir::Type::isF16(), mlir::Type::isF32(), mlir::Type::isF64(), and mlir::Type::isInteger().
Referenced by getSMETileSliceMinNumElts(), and isValidSMETileVectorType().
isValidSMETileVectorType()
bool mlir::arm_sme::isValidSMETileVectorType (VectorType vType)
Returns true if vType is a valid vector type for an SME tile or false otherwise.
Definition at line 34 of file Utils.cpp.
References getSMETileSliceMinNumElts(), and isValidSMETileElementType().
populateVectorTransferLoweringPatterns()
void mlir::arm_sme::populateVectorTransferLoweringPatterns (LLVMTypeConverter & converter, RewritePatternSet & patterns)
Referenced by mlir::populateVectorToLLVMConversionPatterns().