MLIR: mlir::dialect_extension_detail Namespace Reference
mlir::dialect_extension_detail Namespace Reference
Functions
void handleUseOfUndefinedPromisedInterface (Dialect &dialect, TypeID interfaceID, StringRef interfaceName)
Checks if the given interface, which is attempting to be used, is a promised interface of this dialect that has yet to be implemented.
void handleAdditionOfUndefinedPromisedInterface (Dialect &dialect, TypeID interfaceID)
Checks if the given interface, which is attempting to be attached, is a promised interface of this dialect that has yet to be implemented.
Function Documentation
handleAdditionOfUndefinedPromisedInterface()
void mlir::dialect_extension_detail::handleAdditionOfUndefinedPromisedInterface (Dialect & dialect, TypeID interfaceID)
Checks if the given interface, which is attempting to be attached, is a promised interface of this dialect that has yet to be implemented.
If so, the promised interface is marked as resolved.
Definition at line 157 of file Dialect.cpp.
References mlir::Dialect::handleAdditionOfUndefinedPromisedInterface().
Referenced by mlir::OperationName::attachInterface(), and mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::attachInterface().
handleUseOfUndefinedPromisedInterface()
void mlir::dialect_extension_detail::handleUseOfUndefinedPromisedInterface (Dialect & dialect, TypeID interfaceID, StringRef interfaceName)
Checks if the given interface, which is attempting to be used, is a promised interface of this dialect that has yet to be implemented.
If so, emits a fatal error.
Definition at line 152 of file Dialect.cpp.
References mlir::Dialect::handleUseOfUndefinedPromisedInterface().